export const BRANCHES_REPOSITORY = 'BRANCHES_REPOSITORY';
export const USERS_REPOSITORY = 'USERS_REPOSITORY';
export const DEPARTMENTS_REPOSITORY = 'DEPARTMENTS_REPOSITORY';
export const ROLES_REPOSITORY = 'ROLES_REPOSITORY';
export const RIGHTS_REPOSITORY = 'RIGHTS_REPOSITORY';
export const COMPANIES_REPOSITORY = 'COMPANIES_REPOSITORY';
